version: "3.5"

services:
  metrics_broker_build:
    build: ./
    container_name: "metrics_broker_build"
    volumes:
      - dist:/usr/src/app/dist
    env_file:
      - ./var.env

  metrics_broker:
    image: nginx
    container_name: "metrics_broker"
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html:ro

volumes:
  dist:
