version: "3.5"

services:
  metrics_broker_build:
    build: ./
    container_name: "metrics_broker_build"
    volumes:
      - dist:/usr/src/app/dist
    env_file:
      - ./var.env

  metrics_broker_web:
    image: nginx
    container_name: "metrics_broker_web"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/broker.conf
      - ./site.conf:/etc/nginx/snippets/site.conf
      - dist:/usr/share/nginx/html:ro
    env_file:
      - ./var.env
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/broker.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

volumes:
  dist:
